---
title: "LiteratureReview/CitiationAssignment"
author: "Ayron"
date: "Thursday, January 29, 2015"
output: html_document
---

Given the data set GapMinder, I have decided to examine alcocholism and it's relation to low income households and how it affects a persons' nutrition. I searched key phrases such as nutrition, low income, and alcocholism. After reading articles pertaining to my topic, I realized a lot of the readings also had race and gender as variables.Therefore, I think I will expand my research to compare different racial low income families.
 
# References

Alcohol and Nutrition: Health and Disease Prevention - How is alcohol metabolized? (n.d.-a). Retrieved January 22, 2015, from http://www.medicinenet.com/alcohol_and_nutrition/article.htm

Alcohol and Nutrition: Learn About Benefits and Risks. (n.d.-b). Retrieved January 22, 2015, from http://www.medicinenet.com/alcohol_and_nutrition/article.htm

Barnes, G. M., Farrell, M. P., & Banerjee, S. (1994). Family Influences on Alcohol Abuse and Other Problem Behaviors Among Black and White Adolescents in a General Population Sample. Journal of Research on Adolescence, 4(2), 183–201. doi:10.1207/s15327795jra0402_2

Bunout, D. (1999). Nutritional and metabolic effects of alcoholism: their relationship with alcoholic liver disease. Nutrition, 15(7–8), 583–589. doi:10.1016/S0899-9007(99)00090-8

Koch, O., Farré, S., Leo, M. E. D., Palozza, P., Palazzotti, B., Borrelo, S., … Galeotti, T. (2000). REGULATION OF MANGANESE SUPEROXIDE DISMUTASE (MnSOD) IN CHRONIC EXPERIMENTAL ALCOHOLISM: EFFECTS OF VITAMIN E-SUPPLEMENTED AND -DEFICIENT DIETS. Alcohol and Alcoholism, 35(2), 159–163. doi:10.1093/alcalc/35.2.159

Preedy, V. R., Reilly, M. E., Patel, V. B., Richardson, P. J., & Peters, T. J. (1999). Protein metabolism in alcoholism: effects on specific tissues and the whole body. Nutrition, 15(7–8), 604–608. doi:10.1016/S0899-9007(99)00096-9

Weitzman, B. C., Knickman, J. R., & Shinn, M. (1992). Predictors of shelter use among low-income families: psychiatric history, substance abuse, and victimization. American Journal of Public Health, 82(11), 1547–1550. Retrieved from http://www.ncbi.nlm.nih.gov/pmc/articles/PMC1694627/

1. According to a lot of the articles low income families and an alcochol problem have an association. 
2.Also race, gender, and amount of children also are variables throughout these articles. 
In Conclusion, I think I am going to focus my research on the differences in different racial low income families and alcochol abuse. Also, in this research I would like to describe the affects that alcochol has on nutrition. So in my research I might add other topics to search for like comparisions of alcochol abuse in different cultures and races.I like how a lot of the articles link nutrition to alcohol and then also link it to low income families. Therefore, I think my research question will be something pertaining to alcohol and it's effects on low income nutrition.  

